Corrected testcases of the required config analysis, and more accurate circular detection(Bug 499534)
Change-Id: I702a8dc0479d8e6c05c6b5425dc2199901373f87
Signed-off-by: ebensza <bence.janos.szabo@ericsson.com>

diff --git a/regression_test/compileonly/mfgen-tpd/required_config/54/Makefile b/regression_test/compileonly/mfgen-tpd/required_config/54/Makefile
--- a/regression_test/compileonly/mfgen-tpd/required_config/54/Makefile
+++ b/regression_test/compileonly/mfgen-tpd/required_config/54/Makefile
@@ -21,16 +21,17 @@ endif
 # If we used ${MAKE} in the rules below, 'make -n' would succeed once,
 # then fail on every subsequent invocation until a 'make clean' is done. 
 
-# Hierarchy
-#            a----->
-#            |     |
-#            b     d
-#    b:1=>c:1|     |
-#            c<----e
-#                
-
-
-#Result will be: a:Default, b:Default, c:Default, d:Default, e:Default
+# Hierarchy   
+#            a--->e-------->
+#            |    |        |
+#            |    |        |
+#            b<---|---<    |
+#            |    |   |    |f:1
+#            c    |   |b:1 |
+#            |    |   |    |
+#            d>--->   <----f
+# d refers both b and e
+#Result will be: a:Default, b:1, c:Default, d:Default, e:Default, f:1
 MAKEPROG := ${MAKE}
 
 all: CheckTpd 
@@ -41,18 +42,20 @@ BuildTpd:
 
 CheckTpd: BuildTpd
 	if [ `grep -c "EXECUTABLE = binDefault" ./a_binDefault/Makefile` -ne 1 ]; \
-	then echo "Makefilegen required config test 47 failed: Overall verdict: fail" && exit 1; fi
-	if [ `grep -c "EXECUTABLE = binDefault" ./b_binDefault/Makefile` -ne 1 ]; \
-	then echo "Makefilegen required config test 47 failed: Overall verdict: fail" && exit 1; fi
+	then echo "Makefilegen required config test 32 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = bin1" ./b_bin1/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 32 failed: Overall verdict: fail" && exit 1; fi
 	if [ `grep -c "EXECUTABLE = binDefault" ./c_binDefault/Makefile` -ne 1 ]; \
-	then echo "Makefilegen required config test 47 failed: Overall verdict: fail" && exit 1; fi
+	then echo "Makefilegen required config test 32 failed: Overall verdict: fail" && exit 1; fi
 	if [ `grep -c "EXECUTABLE = binDefault" ./d_binDefault/Makefile` -ne 1 ]; \
-	then echo "Makefilegen required config test 47 failed: Overall verdict: fail" && exit 1; fi
+	then echo "Makefilegen required config test 32 failed: Overall verdict: fail" && exit 1; fi
 	if [ `grep -c "EXECUTABLE = binDefault" ./e_binDefault/Makefile` -ne 1 ]; \
-	then echo "Makefilegen required config test 47 failed: Overall verdict: fail" && exit 1; fi
+	then echo "Makefilegen required config test 32 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = bin1" ./f_bin1/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 32 failed: Overall verdict: fail" && exit 1; fi
 
 clean:
-	-rm -rf a_binDefault b_binDefault c_binDefault d_binDefault e_binDefault
+	-rm -rf a_binDefault b_bin1 c_binDefault d_binDefault e_binDefault f_bin1
 
 distclean: clean
 	-rm -f *.out
diff --git a/regression_test/compileonly/mfgen-tpd/required_config/56/Makefile b/regression_test/compileonly/mfgen-tpd/required_config/56/Makefile
--- a/regression_test/compileonly/mfgen-tpd/required_config/56/Makefile
+++ b/regression_test/compileonly/mfgen-tpd/required_config/56/Makefile
@@ -21,22 +21,29 @@ endif
 # If we used ${MAKE} in the rules below, 'make -n' would succeed once,
 # then fail on every subsequent invocation until a 'make clean' is done. 
 
-#This tests that the -b goodConfig exists and it is being used.
-
+# Hierarchy
+#            a--->e------<
+#            |    |(b:1) |
+#            b<---<      |
+#    b:1=>c:1|    |      |
+#            c    |      |d:1=>e:1
+#    c:1=>d:1|    |      |
+#            d>--->------>
+#Result will be: Error
 MAKEPROG := ${MAKE}
 
 all: CheckTpd 
 
 BuildTpd:
 	$(TTCN3_DIR)/bin/ttcn3_makefilegen -f $(MFGEN_FLAGS) $(COVERAGE_FLAG) \
-	-t a.tpd -r -c -b goodConfig
+	-t a.tpd -r -c -W -g 2>&1 | tee output
 
 CheckTpd: BuildTpd
-	if [ `grep -c "EXECUTABLE = binGood" ./binGood/Makefile` -ne 1 ]; \
-	then echo "Makefilegen required config test 1 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c " error: The active build configuration named '1' of project 'e' does not exist" ./output` -ne 1 ]; \
+	then echo "Makefilegen required config test 56 failed: Overall verdict: fail" && exit 1; fi
 
 clean:
-	-rm -rf binGood
+	-rm -rf output a_binDefault b_bin1 c_bin1 d_bin1 e_binDefault
 
 distclean: clean
 	-rm -f *.out
